version: '3.8'

services:
  web:
    build: .
    image: sprc2_web
    container_name: web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - migrationsVolume:/app/migrations
    networks:
      - webNet
      - dbNet
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbVolume:/var/lib/postgresql/data
    networks:
      - dbNet

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - webNet
      - dbNet

volumes:
  dbVolume:
    name: sprc2_dbVolume
  migrationsVolume:
    name: sprc2_migrationsVolume

networks:
  webNet:
  dbNet:
